services:
  backend:
    build: backend
    restart: always
    ports:
      - 8080:8080
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    depends_on:
      - backend
    expose:
      - 3306
      - 33060